In [1]:
import pandas as pd

In [2]:
df_co2 = pd.read_csv('co2.csv')
df_mth = pd.read_csv('methane.csv')
df_nt = pd.read_csv('nitrate_oxide.csv')
df_ghg = pd.read_csv('ghg.csv')
df_gdp = pd.read_csv('gdp.csv')
df_population = pd.read_csv('population_data.csv')

In [3]:
for year in range(1960,2020):
    df_co2[str(year)] = df_co2[str(year)] / df_population[str(year)]
    df_mth[str(year)] = df_mth[str(year)] / df_population[str(year)]
    df_nt[str(year)] = df_nt[str(year)] / df_population[str(year)]
    df_ghg[str(year)] = df_ghg[str(year)] / df_population[str(year)]
    df_gdp[str(year)] = df_gdp[str(year)] / df_population[str(year)]

In [4]:
df_co2_md = pd.read_csv('co2_metadata.csv')
df_co2 = df_co2.merge(df_co2_md,on="Country Code")

In [5]:
df_mth_md = pd.read_csv('methane_metadata.csv')
df_mth = df_mth.merge(df_mth_md,on="Country Code")

In [6]:
df_nt_md = pd.read_csv('nitrate_oxide_metadata.csv')
df_nt = df_nt.merge(df_nt_md,on="Country Code")

In [7]:
df_ghg_md = pd.read_csv('ghg_metadata.csv')
df_ghg = df_ghg.merge(df_ghg_md,on="Country Code")

In [8]:
df_gdp_md = pd.read_csv('gdp_metadata.csv')
df_gdp = df_gdp.merge(df_gdp_md,on="Country Code")

In [9]:
for year in range(1960,1990):
    df_co2 = df_co2.drop(str(year), axis=1)
    df_mth = df_mth.drop(str(year), axis=1)
    df_nt = df_nt.drop(str(year), axis=1)
    df_ghg = df_ghg.drop(str(year), axis=1)
    df_gdp = df_gdp.drop(str(year), axis=1)

In [10]:
for year in range(2013,2020):
    df_co2 = df_co2.drop(str(year), axis=1)
    df_mth = df_mth.drop(str(year), axis=1)
    df_nt = df_nt.drop(str(year), axis=1)
    df_ghg = df_ghg.drop(str(year), axis=1)
    df_gdp = df_gdp.drop(str(year), axis=1)

In [11]:
for column in ['Indicator Code','Unnamed: 64','SpecialNotes','TableName','Unnamed: 5']:
    df_co2 = df_co2.drop(column, axis=1)
    df_mth = df_mth.drop(column, axis=1)
    df_nt = df_nt.drop(column, axis=1)
    df_ghg = df_ghg.drop(column, axis=1)
    df_gdp = df_gdp.drop(column, axis=1)

In [12]:
df_co2 = df_co2[df_co2['Region'].notna()]
df_mth = df_mth[df_mth['Region'].notna()]
df_nt = df_nt[df_nt['Region'].notna()]
df_ghg = df_ghg[df_ghg['Region'].notna()]
df_gdp = df_gdp[df_gdp['Region'].notna()]

In [13]:
df_co2 = pd.melt(df_co2, id_vars = ['Country Name'], value_vars = [str(year) for year in range(1990,2013)])
df_co2 = df_co2.rename(columns={"value": "CO2",'variable':'year'})
df_co2 = df_co2.sort_values(by=['Country Name','year'])

In [14]:
df_mth = pd.melt(df_mth, id_vars = ['Country Name'], value_vars = [str(year) for year in range(1990,2013)])
df_mth = df_mth.rename(columns={"value": "Methane",'variable':'year'})
df_mth = df_mth.sort_values(by=['Country Name','year'])

In [15]:
df_nt = pd.melt(df_nt, id_vars = ['Country Name'], value_vars = [str(year) for year in range(1990,2013)])
df_nt = df_nt.rename(columns={"value": "Nitrate Oxide",'variable':'year'})
df_nt = df_nt.sort_values(by=['Country Name','year'])

In [16]:
df_ghg = pd.melt(df_ghg, id_vars = ['Country Name'], value_vars = [str(year) for year in range(1990,2013)])
df_ghg = df_ghg.rename(columns={"value": "Greenhouse Gases",'variable':'year'})
df_ghg = df_ghg.sort_values(by=['Country Name','year'])

In [17]:
df_gdp = pd.melt(df_gdp, id_vars = ['Country Name'], value_vars = [str(year) for year in range(1990,2013)])
df_gdp = df_gdp.rename(columns={"value": "GDP",'variable':'year'})
df_gdp = df_gdp.sort_values(by=['Country Name','year'])

In [18]:
df = pd.concat([df_co2,df_mth['Methane']],axis=1)

In [19]:
df = pd.concat([df,df_nt['Nitrate Oxide'],df_ghg['Greenhouse Gases'],df_gdp['GDP']],axis=1)

In [20]:
df = df.dropna()

In [21]:
df = df.rename(columns={'CO2':'CO2_emissions','Greenhouse Gases':'GHG_emissions','Methane':'CH4_emissions',
                   'Nitrate Oxide':'N2O_emissions'})
df

,Country Name,year,CO2_emissions,CH4_emissions,N2O_emissions,GHG_emissions,GDP
2605,Afghanistan,2002,0.000047,0.000439,0.000149,0.000612,179.426494
2822,Afghanistan,2003,0.000050,0.000437,0.000141,0.000621,190.684009
3039,Afghanistan,2004,0.000038,0.000426,0.000136,0.000593,211.381970
3256,Afghanistan,2005,0.000052,0.000417,0.000133,0.000576,242.031379
3473,Afghanistan,2006,0.000062,0.000411,0.000130,0.000562,263.733735
3690,Afghanistan,2007,0.000084,0.000408,0.000128,0.000564,359.693480
3907,Afghanistan,2008,0.000152,0.000405,0.000126,0.000551,364.660465
4124,Afghanistan,2009,0.000238,0.000405,0.000118,0.000548,438.076034
4341,Afghanistan,2010,0.000290,0.000462,0.000115,0.000610,543.303042
4558,Afghanistan,2011,0.000406,0.000453,0.000113,0.000597,591.162346
4775,Afghanistan,2012,0.000345,0.000442,0.000110,0.000583,641.872034
3,Albania,1990,0.001678,0.000775,0.000475,0.003381,617.230436
220,Albania,1991,0.001312,0.000734,0.000308,0.002533,336.586995
437,Albania,1992,0.000775,0.000699,0.000312,0.001918,200.852220
654,Albania,1993,0.000724,0.000726,0.000289,0.001880,367.279225
871,Albania,1994,0.000600,0.000868,0.000333,0.002118,586.416340
1088,Albania,1995,0.000655,0.000869,0.000308,0.002014,750.604449
1305,Albania,1996,0.000637,0.000827,0.000284,0.001953,1009.977668
1522,Albania,1997,0.000490,0.000781,0.000270,0.001747,717.380567
1739,Albania,1998,0.000560,0.000758,0.000297,0.001677,813.790264
1956,Albania,1999,0.000960,0.000758,0.000298,0.002089,1033.241693
2173,Albania,2000,0.000978,0.000845,0.000409,0.002716,1126.683318
2390,Albania,2001,0.001053,0.000766,0.000303,0.002229,1281.659393
2607,Albania,2002,0.001230,0.000765,0.000324,0.002459,1425.124849
2824,Albania,2003,0.001413,0.000814,0.000314,0.002577,1846.118813
3041,Albania,2004,0.001376,0.000816,0.000340,0.002445,2373.579844
3258,Albania,2005,0.001412,0.000823,0.000341,0.002759,2673.787283
3475,Albania,2006,0.001303,0.000830,0.000359,0.002682,2972.743265
3692,Albania,2007,0.001322,0.000844,0.000360,0.003326,3595.037163
3909,Albania,2008,0.001484,0.000854,0.000377,0.002761,4370.540087
...,...,...,...,...,...,...,...
3687,Zambia,2006,0.000188,0.001659,0.001890,0.025859,1047.919187
3904,Zambia,2007,0.000154,0.001639,0.001855,0.027274,1124.290586
4121,Zambia,2008,0.000169,0.000476,0.000611,0.024996,1394.000608
4338,Zambia,2009,0.000190,0.000476,0.000613,0.020137,1159.907762
4555,Zambia,2010,0.000198,0.000472,0.000605,0.023503,1489.459070
4772,Zambia,2011,0.000209,0.000463,0.000593,0.022821,1672.949830
4989,Zambia,2012,0.000254,0.000453,0.000580,0.022140,1763.094184
216,Zimbabwe,1990,0.001500,0.000983,0.000662,0.003365,841.972990
433,Zimbabwe,1991,0.001494,0.000829,0.000523,0.003196,809.052125
650,Zimbabwe,1992,0.001561,0.000989,0.000706,0.003511,619.372594
867,Zimbabwe,1993,0.001475,0.000668,0.000409,0.002721,591.720162
1084,Zimbabwe,1994,0.001580,0.000706,0.000454,0.002682,611.865711
1301,Zimbabwe,1995,0.001326,0.000720,0.000459,0.002662,623.209967
1518,Zimbabwe,1996,0.001299,0.000768,0.000465,0.002649,741.095727
1735,Zimbabwe,1997,0.001236,0.000757,0.000451,0.002529,731.948380
1952,Zimbabwe,1998,0.001213,0.000787,0.000487,0.006503,544.984163
2169,Zimbabwe,1999,0.001339,0.000867,0.000534,0.005644,580.070718
2386,Zimbabwe,2000,0.001172,0.000814,0.000480,0.004329,563.057741
2603,Zimbabwe,2001,0.001056,0.000850,0.000524,0.004902,568.385909
2820,Zimbabwe,2002,0.001001,0.000803,0.000464,0.004206,530.530579
3037,Zimbabwe,2003,0.000889,0.000769,0.000431,0.004024,478.007405
3254,Zimbabwe,2004,0.000789,0.000792,0.000462,0.005137,482.998411
3471,Zimbabwe,2005,0.000892,0.000800,0.000476,0.004960,476.555324
3688,Zimbabwe,2006,0.000859,0.000696,0.000339,0.004569,447.854924
3905,Zimbabwe,2007,0.000807,0.000691,0.000340,0.004970,431.787188
4122,Zimbabwe,2008,0.000628,0.000683,0.000337,0.005561,356.693350
4339,Zimbabwe,2009,0.000447,0.000669,0.000335,0.005421,771.598786
4556,Zimbabwe,2010,0.000613,0.000663,0.000330,0.005593,948.331854
4773,Zimbabwe,2011,0.000742,0.000660,0.000328,0.005550,1093.654002
4990,Zimbabwe,2012,0.000594,0.000655,0.000326,0.005494,1304.969802

In [24]:
df.to_csv('data.csv',sep=';',index=False)